train:
  data_path: "data/Dataset-Mental-Disorders.csv"
  batch_size: 10
  epochs: 10

infer:
  model_path: "disorder_classifier.h5"
  test_dir: "test_data/"
  output_file: "infer_results.txt"

num_classes: 4
patience: 5
val_split: 0.2
random_state: 42
